### ISSUE TITLE
json formatter for symfony?

### ISSUE THREAD

**Issue by klausbreyer** [maxbanton/cwh#27]
hey there, 

first of all: awesome work, thank you! from zero to working in less than an hour. 

second: is it possible to use a json formatter?

I tried this: 
services.yml
```

    cloudwatch_formatter:
        class: Monolog\Formatter\JsonFormatter

```

config.yml
```

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: notice
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        custom:
            type: service
            id: cloudwatch_handler
            level: notice
            formatter: cloudwatch_formatter
```

sadly I got this error: 
```

  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Invalid configuration for path "monolog.handlers.custom": Service handlers can not have a formatter configured in the bundle, you must reconfigur
  e the service itself instead
```

**Comment by maxbanton** [comment]
Hi!
Seems like something wrong with your configuration.
CloudWatchHandler [extends AbstractProcessingHandler](https://github.com/maxbanton/cwh/blob/master/src/Handler/CloudWatch.php#L10), so you are able to call `setFormatter` method. 
Plain PHP example:
```php
// Instantiate handler
$handler = new CloudWatch($client, 'php-logtest', 'ec2-instance-2', 1, 5, ['php' => 'test']);

$formatter = new \Monolog\Formatter\JsonFormatter();

$handler->setFormatter($formatter);
```

Max.

**Comment by vineus** [comment]
Hey @klausbreyer : I'm having exactly the same issue, what did you do to make it work in the end ? (cwh logs are in an hybrid text/json format that is not at all practical to feed into an ElasticSearch cluster :-) )

Thanks a lot for your help!

**Comment by vineus** [comment]
Ok, I finally got it!

Following symfony doc here: https://symfony.com/doc/2.8/service_container/configurators.html

Create a configurator to set the handler properties:

```php
<?php

namespace Bundle\Utils;

use Monolog\Handler\AbstractProcessingHandler;

class JsonLogConfigurator
{
    public function configure(AbstractProcessingHandler $handler)
    {
        $formatter = new \Monolog\Formatter\JsonFormatter();
        $handler->setFormatter($formatter);
    }
}
```

Use your configurator in the service declaration:

```yml
    json_log_configurator:
        class: Bundle\Utils\JsonLogConfigurator

    cloudwatch_handler_prod:
        class: Maxbanton\Cwh\Handler\CloudWatch
        configurator: ['@json_log_configurator', configure]
        arguments:
            - ...
```
