### ISSUE TITLE
Exception: Log events in a single PutLogEvents request must be in chronological order

### ISSUE THREAD

**Issue by renatogcarvalho** [maxbanton/cwh#32]
Hello folks,

On a Symfony application, after I enabled this library in my production environment I started to get a lot of Exceptions such as the one below:

[2018-02-26 11:44:55] prod.EMERGENCY: Message: Error executing "PutLogEvents" on "https://logs.us-west-2.amazonaws.com"; AWS HTTP error: Client error: `POST https://logs.us-west-2.amazonaws.com` resulted in a `400 Bad Request` response: {"__type":"InvalidParameterException","message":"Log events in a single PutLogEvents request must be in chronological or (truncated...)  InvalidParameterException (client): Log events in a single PutLogEvents request must be in chronological order. - {"__type":"InvalidParameterException","message":"Log events in a single PutLogEvents request must be in chronological order."} []

Below is my current configuration:

```yaml
services:
    monolog.formatter.api:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%extra.route%%] [%%extra.server_hostname%%] [%%extra.request%%] %%level_name%%: %%message%% %%context%% %%extra%%\n"

    cloudwatchlogs.api:
        class: Maxbanton\Cwh\Handler\CloudWatch
        arguments:
            - '@aws.cloudwatchlogs'
            - '/path'
            - 'api'
            - 30
            - 10000
            - { mytag: 'api' }
            - DEBUG
        calls:
            - ['setFormatter', ['@monolog.formatter.api']]

monolog:
    handlers:
        api:
            type:         service
            id:           cloudwatchlogs.api
            formatter:    ~
```

Any ideas on why would this happen? One of my channels generates a lot of DEBUG messages but I presume this wouldn't really be a problem?

Thank you in advance.

Renato.
